language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION! build

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
    # Pants cache
    - $HOME/.cache
